SWIDEA_SITE/posts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name="posts"
urlpatterns = [
    path('', views.home, name="home"),
    path('create', views.create, name="create"),
    path('post/<int:id>', views.detail, name="detail"),
    path('update/<int:id>', views.update, name="update"),
    path('delete/<int:id>', views.delete, name="delete"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SWIDEA_SITE/posts/models.py
from django.db import models
from tabnanny import verbose

class Post(models.Model):
    title = models.CharField(max_length=100, verbose_name="아이디어명")
    photo = models.ImageField(blank=True, upload_to='posts/%Y%m%d', verbose_name="사진")
    description = models.TextField(verbose_name="아이디어 설명")
    interest = models.IntegerField(verbose_name="아이디어 관심도")
    expected_tool = models.CharField(max_length=50, verbose_name="예상 개발툴")

SWIDEA_SITE/posts/views.py
from django.shortcuts import render,redirect
from .models import Post

# Create your views here.
def home(request):
    posts = Post.objects.all()
    context = {
        "posts":posts
    }
    return render(request, template_name="posts/home.html", context=context)

def create(request):
    if request.method == "POST":
        title = request.POST["title"]
        req_photo = request.FILES["photo"]
        description = request.POST["description"]
        interest = request.POST["interest"]
        expected_tool = request.POST["expected_tool"]

        Post.objects.create(title= title, photo=req_photo, description=description, interest=interest, expected_tool=expected_tool)
        
        return redirect("/")

    context = {}

    return render(request, template_name="posts/create.html", context=context)


def detail(request, id):
    posts = Post.objects.get(id=id)
    context = {
    }
    return render(request, template_name="posts/detail.html", context=context)


def update(request, id):
    if request.method == "POST":
        title = request.POST["title"]
        req_photo = request.FILES["photo"]
        description = request.POST["description"]
        interest = request.POST["interest"]
        expected_tool = request.POST["expected_tool"]

        Post.objects.filter(id=id).update(title= title, photo=req_photo, description=description, interest=interest, expected_tool=expected_tool)
        return redirect(f"/post/{id}")
    
    elif request.method == "GET":
        post = Post.objects.get(id=id)
        context = {
            "post": post
        }
        return render(request, template_name="posts/update.html", context=context)

def delete(request, id):
    if request.method == "POST":
        Post.objects.filter(id=id).delete()
        return redirect("/")

SWIDEA_SITE/posts/templates/posts/create.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- <link rel="stylesheet" href="{% static 'css/create.css' %}" /> -->
    <title>게시글 올리기</title>
  </head>
  <body>
    <navbar>
      <div class="logo">
        <a href="{% url 'posts:home' %}">My SW Idea Manage</a>
      </div>
      <a href="{% url 'posts:create' %}"> 아이디어 등록 </a>
      <a href="{% url 'posts:home' %}"> 아이디어 관리 </a>
      <a href="{% url 'posts:create' %}"> 개발툴 등록 </a>
    </navbar>

    <div class="page_title">
      <h1>Idea Register</h1>
      <p>
        아이디어 등록 페이지 입니다. 당신의 아이디어를 잊지 말고 기록하세요!
      </p>
    </div>

    <form
      action="{% url 'posts:create' %}"
      method="post"
      enctype="multipart/form-data"
    >
      {% csrf_token %}
      <h2>
        아이디어명:
        <input type="text" name="title" placeholder="아이디어명" />
      </h2>
      <p>
        <input type="file" name="photo" />
      </p>
      <p>
        아이디어 설명:
        <textarea name="description" cols="50" rows="20"></textarea>
      </p>

      <p>
        아이디어 관심도:
        <input type="number" name="interest" placeholder="아이디어 관심도" />
      </p>
      <p>
        예상 개발툴:
        <input type="text" name="expected_tool" placeholder="예상 개발툴:" />
      </p>

      <div>
        <input type="submit" value="제출" />
      </div>
    </form>
  </body>
</html>

SWIDEA_SITE/posts/templates/posts/detail.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- <link rel="stylesheet" href="{% static 'css/detail.css' %}" /> -->
    <title>상세화면</title>
  </head>
  <body>
    <navbar>
      <div class="logo">
        <a href="{% url 'posts:home' %}">My SW Idea Manage</a>
      </div>
      <a href="{% url 'posts:create' %}"> 아이디어 등록 </a>
      <a href="{% url 'posts:home' %}"> 아이디어 관리 </a>
      <a href="{% url 'posts:create' %}"> 개발툴 등록 </a>
    </navbar>

    <div class="page_title">
      <h1>Idea Detail</h1>
      <p>
        아이디어 세부내용 페이지 입니다. 당신이 구현하려 한 아이디어들을 자세히
        살펴보세요.
      </p>
    </div>

    <article>
      {% if post.photo %}
      <p>
        <img src="{{ post.photo.url }}" />
      </p>
      {% endif %}

      <h2>{{ post.title }}</h2>
      <div>
        <p>1) 아이디어 관심도 {{ post.interest }}</p>
        <p>2) 예상 개발 툴 {{ post.expected_tool }}</p>
        <p>3) 아이디어 설명 {{ post.description }}</p>
      </div>
      <div></div>
      <div style="display: flex">
        <form action="{% url 'posts:delete' post.id %}" method="post">
          {% csrf_token %}
          <button>삭제</button>
        </form>
        <a href="{% url 'posts:home' %}">목록</a>
        <a href="{% url 'posts:update' post.id %}">수정</a>
      </div>
    </article>
  </body>
</html>

SWIDEA_SITE/posts/templates/posts/home.html
<!DOCTYPE html>
<html lang="ko">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/home.css' %}" />
    <title>홈 화면</title>
  </head>
  <body style="background-image: url('{% static 'image/sourcecode_.jpg' %}')">
    <navbar>
      <div class="logo">
        <a href="{% url 'posts:home' %}">My SW Idea Manage</a>
      </div>
      <a href="{% url 'posts:create' %}"> 아이디어 등록 </a>
      <a href="{% url 'posts:home' %}"> 아이디어 관리 </a>
      <a href="{% url 'posts:create' %}"> 개발툴 등록 </a>
    </navbar>

    <div class="page_title">
      <h1>Idea List</h1>
      <p>나의 아이디어를 잊지 말고 기록해보세요</p>
    </div>

    {% for post in posts %}
    <article>
      {% if post.photo %}
      <p>
        <img src="{{ post.photo.url }}" />
      </p>
      {% endif %}

      <div>
        <a href="{% url 'posts:detail' post.id %}">
          <h1>{{post.title}}</h1>
        </a>
        <p>예상 개발 툴: {{post.expected_tool}}</p>
        <!-- TODO: 아이디어 관심도 ajax 이용해서 고치기-->
        <p>아이디어 관심도: {{post.interest}}</p>
      </div>
    </article>
    {% endfor %}
  </body>
</html>

SWIDEA_SITE/posts/templates/posts/update.html
<!DOCTYPE html>
<html lang="ko">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- <link rel="stylesheet" href="{% static 'css/update.css' %}" /> -->
    <title>게시글 올리기</title>
  </head>
  <body>
    <navbar>
      <div class="logo">
        <a href="{% url 'posts:home' %}">My SW Idea Manage</a>
      </div>
      <a href="{% url 'posts:create' %}"> 아이디어 등록 </a>
      <a href="{% url 'posts:home' %}"> 아이디어 관리 </a>
      <a href="{% url 'posts:create' %}"> 개발툴 등록 </a>
    </navbar>

    <div class="page_title">
      <h1>Idea Detail Update</h1>
      <p>
        아이디어 세부내용 수정 페이지 입니다. 아이디어를 구체화하거나 내용을
        변경해 보아요.
      </p>
    </div>

    <form action="{% url 'posts:update' post.id %}" method="post">
      {% csrf_token %}
      <h2>
        아이디어명:
        <input
          type="text"
          name="title"
          placeholder="아이디어명"
          value="{{post.title}}"
        />
      </h2>
      <!-- <p>
        <input type="file" name="photo" />
      </p> -->
      <p>
        아이디어 설명:
        <textarea
          name="description"
          cols="50"
          rows="20"
          value="{{post.description}}"
        ></textarea>
      </p>

      <p>
        아이디어 관심도:
        <input
          type="number"
          name="interest"
          placeholder="아이디어 관심도"
          value="{{post.interest}}"
        />
      </p>
      <p>
        예상 개발툴:
        <input
          type="text"
          name="expected_tool"
          placeholder="예상 개발툴:"
          value="{{post.expected_tool}}"
        />
      </p>

      <div>
        <input type="submit" value="제출" />
      </div>
    </form>
    <a href="{% url 'posts:home' %}">Home</a>
  </body>
</html>