myMovieReviews/reviews/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path('', views.home, name="home"),
    path('create', views.create, name="create"),
    path('review/<int:id>', views.detail, name="detail"),
    path('update/<int:id>', views.update, name="update"),
    path('delete/<int:id>', views.delete, name="delete"),
]

myMovieReviews/reviews/models.py
from tabnanny import verbose
from django.db import models
from decimal import Decimal

# Create your models here.
class Review(models.Model):
    title = models.CharField(max_length=100, verbose_name="제목")
    release_yr = models.IntegerField(verbose_name="개봉년도")
    genre = models.CharField(max_length=50, verbose_name="장르")
    rating = models.DecimalField(max_digits=10, decimal_places=1, default=Decimal(0.0), verbose_name="별점")
    running_time = models.IntegerField(verbose_name="러닝타임")
    content = models.TextField(verbose_name="리뷰")
    director = models.CharField(max_length=100, verbose_name="감독")
    actors = models.CharField(max_length=100, verbose_name="배우")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

myMovieReviews/reviews/views.py
from django.shortcuts import render, redirect
from .models import Review

def home(request):
    reviews = Review.objects.all()

    context = {
        "reviews":reviews
    }
    return render(request, template_name="reviews/home.html", context=context)


def create(request):
    if request.method == "POST":
        print(request.POST)
        title = request.POST["title"]
        release_yr = request.POST["release_yr"]
        genre = request.POST["genre"]
        rating = request.POST["rating"]
        running_time = request.POST["running_time"]
        content = request.POST["content"]
        director = request.POST["director"]
        actors = request.POST["actors"]

        Review.objects.create(title= title, release_yr=release_yr, genre=genre, rating=rating, running_time=running_time, content=content, director=director, actors=actors)
        
        return redirect("/")

    context = {}

    return render(request, template_name="reviews/create.html", context=context)

def detail(request, id):
    review = Review.objects.get(id=id)
    context = {
        "review": review
    }
    return render(request, template_name="reviews/detail.html", context=context)

def update(request, id):
        if request.method == "POST":
            title = request.POST["title"]
            release_yr = request.POST["release_yr"]
            genre = request.POST["genre"]
            rating = request.POST["rating"]
            running_time = request.POST["running_time"]
            content = request.POST["content"]
            director = request.POST["director"]
            actors = request.POST["actors"]

            Review.objects.filter(id=id).update(title= title, release_yr=release_yr, genre=genre, rating=rating, running_time=running_time, content=content, director=director, actors=actors)

            return redirect(f"/review/{id}")
    
        elif request.method == "GET":
            review = Review.objects.get(id=id)
            context = {
                "review":review
            }
            return render(request, template_name="reviews/update.html", context=context)

def delete(request, id):
    if request.method == "POST":
        Review.objects.filter(id=id).delete()
        return redirect("/")

myMovieReviews/reviews/templates/reviews/create.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>게시글 올리기</title>
  </head>
  <body>
    <div>
      <a href="{% url 'reviews:home' %}"><h3>my Movie reviews</h3></a>
    </div>
    <form action="/create" method="post">
      {% csrf_token %}
      <h2>제목: <input type="text" name="title" /></h2>
      <p>
        개봉년도: <input type="text" name="release_yr" /> 장르:
        <input type="text" name="genre" /> 별점:
        <input type="text" name="rating" /> 러닝타임:
        <input type="text" name="running_time" />
      </p>
      <div>
        <p>리뷰:</p>
        <textarea name="content" id="" cols="30" rows="10"></textarea>
      </div>
      감독: <input type="text" name="director" /> 배우:
      <input type="text" name="actors" />

      <div style="margin-top: 10px">
        <input type="submit" value="Save" />
      </div>
    </form>
  </body>
</html>

myMovieReviews/reviews/templates/reviews/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>상세화면</title>
  </head>
  <body>
    <div>
      <a href="{% url 'reviews:home' %}"><h3>my Movie reviews</h3></a>
    </div>
    <article>
      <div>
        <h2>{{ review.title }}</h2>
        <div style="display: flex">
          <button>
            <a href="{% url 'reviews:update' review.id %}">수정</a>
          </button>
          <form action="{% url 'reviews:delete' review.id %}" method="post">
            {% csrf_token %}
            <button>삭제</button>
          </form>
        </div>
      </div>
      <p>개봉년도: {{ review.release_yr }}</p>
      <p>감독: {{ review.director }}</p>
      <p>주연: {{ review.actors }}</p>
      <p>장르: {{ review.genre }}</p>
      <p>별점: {{ review.rating }}</p>
      <p>러닝타임: {{ review.running_time }}</p>
      <div>{{ review.content }}</div>
    </article>
  </body>
</html>

myMovieReviews/reviews/templates/reviews/home.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>홈 화면</title>
  </head>
  <body>
    <div>
      <a href="{% url 'reviews:home' %}"><h3>my Movie reviews</h3></a>
    </div>
    {% for review in reviews %}
    <article>
      <h1><a href="/review/{{review.id}}">{{ review.title }}</a></h1>
      <p>개봉년도 {{ review.release_yr }}</p>
      <p>장르 {{ review.genre }}</p>
      <p>별점 {{ review.rating }}</p>
    </article>
    {% endfor %}
    <a href="/create">Add a New review</a>
  </body>
</html>

myMovieReviews/reviews/templates/reviews/update.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>게시글 올리기</title>
  </head>
  <body>
    <div>
      <a href="{% url 'reviews:home' %}"><h3>my Movie reviews</h3></a>
    </div>
    <form action="/update/{{review.id}}" method="post">
      {% csrf_token %}
      <h2>
        제목:
        <input
          type="text"
          name="title"
          placeholder="제목"
          value="{{review.title}}"
        />
      </h2>
      <p>
        개봉년도:
        <input
          type="text"
          name="release_yr"
          placeholder="개봉년도"
          value="{{review.release_yr}}"
        />
        장르:
        <input
          type="text"
          name="genre"
          placeholder="장르"
          value="{{review.genre}}"
        />
        별점:
        <input
          type="text"
          name="rating"
          placeholder="별점"
          value="{{review.rating}}"
        />
        러닝타임:
        <input
          type="text"
          name="running_time"
          placeholder="러닝타임"
          value="{{review.running_time}}"
        />
      </p>
      <div>
        리뷰:
        <textarea name="content" id="" cols="30" rows="10">
          {{review.content}}</textarea
        >
      </div>
      <p>
        감독:
        <input
          type="text"
          name="director"
          placeholder="감독"
          value="{{review.director}}"
        />
        배우:
        <input
          type="text"
          name="actors"
          placeholder="배우"
          value="{{review.actors}}"
        />
      </p>
      <div>
        <input type="submit" value="Save" />
      </div>
    </form>
  </body>
</html>